### ISSUE TITLE
Reload button too close to tap area

### ISSUE THREAD

**Issue by SadChimera** [Luca1152/gravity-box#65]
I tend to keep pressing the reload button on accident when I'm fairly close to beating a level. To note, the nature of the game makes reloads fairly unnecessary. You lose nothing by moving the button to the top of the screen. Just food for thought. I love the no-ad minimalist design and would be interested in a donation button in the menu.   
  
The game also doesn't seem to acknowledge that I've already given it a 5 star rating, it continues to ask me for a rating.

**Comment by Luca1152** [comment]
I think that the restart button is pretty useful, especially when you start falling down (on bigger maps) and realize that there is no point in waiting, as you'll lose anyway. And it will become more useful once I implement leaderboards, so I am not really willing to remove it. 

However, moving it to the top right could do the trick, but I fear that it a bit hard to reach (that's why I added it in the bottom right).

The game, however, isn't ad-free :). I guess that the ads are pretty rare (at least compared to other games)?  And there is already a donation button in the menu (that removes the ads), only that it appears when you press the menu button (the one with 3 lines). Maybe I should add a text in one level to tell the player about the button.

About the game acknowledging that you already rate... That's pretty weird, as this shouldn't happen (being asked continuously to rate it)... I'll look into it.

**Comment by SadChimera** [comment]
Odd, level 95 and I've yet to see an advertisement

**Comment by Luca1152** [comment]
Are you sure you are connected to the internet? Maybe this could be the issue. Also, do rewarded ads (skipping a level by watching an ad) work?

**Comment by SadChimera** [comment]
Skipping a level will in fact show an advertisement for me. I've used both cellular and wifi without seeing advertisements which is odd
